### signup
POST http://[::1]:4008/signup
Content-Type: application/json
Accept: application/json

{
  "username": "User 1",
  "password": "IDnowLOV123!",
  "email": "user1@gmail.com"
}

### login and get auth_token
POST http://[::1]:4008/users/login
Content-Type: application/json
Accept: application/json

{
  "password": "IDnowLOV123!",
  "email": "user1@gmail.com"
}
> {% client.global.set("auth_token", response.body.token); %}


### whoAmI
GET http://[::1]:4008/whoAmI
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}


### CREATE BOOK
POST http://[::1]:4008/books
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "My First Book",
  "description": "my first book description",
  "isbn": "123141"
}

### GET BOOKS
GET http://[::1]:4008/books
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### DELETE BOOK
DELETE http://[::1]:4008/books/13
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### SEARCH BOOK
GET http://[::1]:4008/books/search
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Jane"
}

### CREATE LIST
POST http://[::1]:4008/lists
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "User 2 list",
  "description": "my first list description"
}

### GET LIST
GET http://[::1]:4008/lists/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### DELETE LIST
DELETE http://[::1]:4008/lists/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

### CREATE ENTRY
POST http://[::1]:4008/lists/11/entries
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "bookId": 13,
  "listId": 11
}

### DELETE ENTRY
DELETE http://[::1]:4008/lists/11/entries/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}


### GET ENTRIES
GET http://[::1]:4008/lists/11/entries
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}




